apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userservice-monitor
  namespace: suryadasari31-dev
spec:
  selector:
    matchLabels:
      app: userservice
  namespaceSelector:
    matchNames:
      - suryadasari31-dev
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s

