apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: docker.io/suryadasari31/nextgen-authservice:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: USERSERVICE_URL
              value: http://userservice:9002
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  selector:
    app: authservice
  ports:
    - name: http
      port: 9001
      targetPort: 9001
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: authservice
spec:
  to:
    kind: Service
    name: authservice
  port:
    targetPort: http
  tls:
    termination: edge

