apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextgen-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextgen-ui
  template:
    metadata:
      labels:
        app: nextgen-ui
    spec:
      containers:
        - name: nextgen-ui
          image: docker.io/suryadasari31/nextgen-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: nextgen-ui
spec:
  selector:
    app: nextgen-ui
  ports:
    - name: http
      port: 9080
      targetPort: 9080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nextgen-ui
spec:
  to:
    kind: Service
    name: nextgen-ui
  port:
    targetPort: http
  tls:
    termination: edge

