apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiservice
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
        - name: apiservice
          image: docker.io/suryadasari31/nextgen-apiservice:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: AUTH_SERVICE_URL
              value: http://authservice:9001
            - name: USER_SERVICE_URL
              value: http://userservice:9002
---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
spec:
  selector:
    app: apiservice
  ports:
    - name: http
      port: 9000
      targetPort: 9000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apiservice
spec:
  to:
    kind: Service
    name: apiservice
  port:
    targetPort: http
  tls:
    termination: edge

